# Zepto Data & AI Platform
## Module 1: Data Pipeline

This project demonstrates an end-to-end data pipeline involving web scraping, data cleaning, currency conversion, relational database storage, and SQL/Pandas analysis.

In [31]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import sqlite3

In [32]:
url = "https://books.toscrape.com/"
response = requests.get(url)
print("Status code:",response.status_code)
print(response.text[:200])

Status code: 200
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if I

In [33]:
soup = BeautifulSoup(response.text, "html.parser")

books = soup.find_all("article", class_="product_pod")

print("Number of books found:", len(books))

first_book = books[0]

print(first_book.prettify())

Number of books found: 20
<article class="product_pod">
 <div class="image_container">
  <a href="catalogue/a-light-in-the-attic_1000/index.html">
   <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
  </a>
 </div>
 <p class="star-rating Three">
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
 </p>
 <h3>
  <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
   A Light in the ...
  </a>
 </h3>
 <div class="product_price">
  <p class="price_color">
   Â£51.77
  </p>
  <p class="instock availability">
   <i class="icon-ok">
   </i>
   In stock
  </p>
  <form>
   <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
    Add to basket
   </button>
  </form>
 </div>
</article>

In [34]:
title = first_book.find("h3").find("a")["title"]
price = first_book.find("p", class_="price_color").text.strip()
rating_class = first_book.find("p", class_="star-rating")["class"]
availability = first_book.find("p", class_="instock availability").text.strip()

print("Title:", title)
print("Price:", price)
print("Rating:", rating_class)
print("Availability:", availability)

Title: A Light in the Attic
Price: Â£51.77
Rating: ['star-rating', 'Three']
Availability: In stock

In [35]:
def extract_book_details(book):
    title = book.find("h3").find("a")["title"]

    price = book.find("p", class_="price_color").text.strip()

    rating = book.find("p", class_="star-rating")["class"][1]

    availability = book.find(
        "p", class_="instock availability"
    ).text.strip()

    return {
        "title": title,
        "price": price,
        "star_rating": rating,
        "availability": availability
    }

In [36]:
first_book_data = extract_book_details(first_book)

print(first_book_data)

{'title': 'A Light in the Attic', 'price': 'Â£51.77', 'star_rating': 'Three', 'availability': 'In stock'}

In [37]:
all_books = []

for book in books:
    book_data = extract_book_details(book)
    all_books.append(book_data)

print("Total books extracted:", len(all_books))

Total books extracted: 20

In [38]:
def scrape_page(url):
    response = requests.get(url)

    if response.status_code != 200:
        print("Failed to fetch:", url)
        return []

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    page_books = []

    for book in books:
        book_data = extract_book_details(book)
        page_books.append(book_data)

    return page_books

In [39]:
page_url = "https://books.toscrape.com/catalogue/page-1.html"

page_data = scrape_page(page_url)

print("Books scraped:", len(page_data))
print(page_data[:2])

Books scraped: 20
[{'title': 'A Light in the Attic', 'price': 'Â£51.77', 'star_rating': 'Three', 'availability': 'In stock'}, {'title': 'Tipping the Velvet', 'price': 'Â£53.74', 'star_rating': 'One', 'availability': 'In stock'}]

In [40]:
all_books = []

for page_number in range(1, 6):
    url = f"https://books.toscrape.com/catalogue/page-{page_number}.html"

    print("Scraping page:", page_number)

    page_data = scrape_page(url)

    all_books.extend(page_data)

print("Total books scraped:", len(all_books))

Scraping page: 1
Scraping page: 2
Scraping page: 3
Scraping page: 4
Scraping page: 5
Total books scraped: 100

In [41]:
def extract_book_details(book):
    title = book.find("h3").find("a")["title"]

    price = book.find("p", class_="price_color").text.strip()

    rating = book.find("p", class_="star-rating")["class"][1]

    availability = book.find(
        "p", class_="instock availability"
    ).text.strip()

    product_link = book.find("h3").find("a")["href"]

    return {
        "title": title,
        "price": price,
        "star_rating": rating,
        "availability": availability,
        "product_link": product_link
    }

In [42]:
def get_category(product_link):
    base_url = "https://books.toscrape.com/"
    full_url = urljoin(base_url)

    response = requests.get(full_url)

    if response.status_code != 200:
        return "Unknown"

    soup = BeautifulSoup(response.text, "html.parser")

    breadcrumbs = soup.find("ul", class_="breadcrumb")

    category = breadcrumbs.find_all("li")[2].get_text(strip=True)

    return category

In [43]:
def extract_book_details(book):
    title = book.find("h3").find("a")["title"]

    price = book.find("p", class_="price_color").text.strip()

    rating = book.find("p", class_="star-rating")["class"][1]

    availability = book.find(
        "p", class_="instock availability"
    ).text.strip()

    product_link = book.find("h3").find("a")["href"]

    return {
        "title": title,
        "price": price,
        "star_rating": rating,
        "availability": availability,
        "product_link": product_link
    }

In [44]:
def scrape_page(url):
    response = requests.get(url)

    if response.status_code != 200:
        print("Failed to fetch:", url)
        return []

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    page_books = []

    for book in books:
        book_data = extract_book_details(book)
        page_books.append(book_data)

    return page_books

In [45]:
all_books = []

for page_number in range(1, 6):

    url = f"https://books.toscrape.com/catalogue/page-{page_number}.html"

    print(f"Scraping page {page_number}...")

    page_data = scrape_page(url)

    all_books.extend(page_data)

print("Total books scraped:", len(all_books))

Scraping page 1...
Scraping page 2...
Scraping page 3...
Scraping page 4...
Scraping page 5...
Total books scraped: 100

In [46]:
from urllib.parse import urljoin

def get_category(product_link):
    base_url = "https://books.toscrape.com/catalogue/" # Corrected base_url
    full_url = urljoin(base_url, product_link)

    response = requests.get(full_url)

    if response.status_code != 200:
        return "Unknown"

    soup = BeautifulSoup(response.text, "html.parser")

    breadcrumbs = soup.find("ul", class_="breadcrumb")

    if breadcrumbs:
        items = breadcrumbs.find_all("li")

        if len(items) >= 3:
            return items[2].get_text(strip=True)

    return "Unknown"

In [47]:
for i, book in enumerate(all_books):

    category = get_category(book["product_link"])

    book["category"] = category

    if (i + 1) % 10 == 0:
        print(f"Processed {i + 1} books")

Processed 10 books
Processed 20 books
Processed 30 books
Processed 40 books
Processed 50 books
Processed 60 books
Processed 70 books
Processed 80 books
Processed 90 books
Processed 100 books

In [48]:
for i, book in enumerate(all_books):

    category = get_category(book["product_link"])

    book["category"] = category

    if (i + 1) % 10 == 0:
        print(f"Processed {i + 1} books")

Processed 10 books
Processed 20 books
Processed 30 books
Processed 40 books
Processed 50 books
Processed 60 books
Processed 70 books
Processed 80 books
Processed 90 books
Processed 100 books

In [49]:
df = pd.DataFrame(all_books)

print(df.head())
print("\nDataset Shape:", df.shape)
print("\nColumns:", df.columns.tolist())

                                   title    price star_rating availability  \
0                   A Light in the Attic  Â£51.77       Three     In stock
1                     Tipping the Velvet  Â£53.74         One     In stock
2                             Soumission  Â£50.10         One     In stock
3                          Sharp Objects  Â£47.82        Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23        Five     In stock

                                        product_link            category
0               a-light-in-the-attic_1000/index.html              Poetry
1                  tipping-the-velvet_999/index.html  Historical Fiction
2                          soumission_998/index.html             Fiction
3                       sharp-objects_997/index.html             Mystery
4  sapiens-a-brief-history-of-humankind_996/index...             History

Dataset Shape: (100, 6)

Columns: ['title', 'price', 'star_rating', 'availability', 'product_link', 'category']

In [50]:
import re

def clean_price(price):
    try:
        numeric_price = re.sub(r"[^0-9.]", "", price)
        return float(numeric_price)
    except:
        return None

df["price_gbp"] = df["price"].apply(clean_price)

In [51]:
rating_mapping = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["rating"] = df["star_rating"].map(rating_mapping)

In [52]:
numeric_columns = ["price_gbp", "rating"]

for column in numeric_columns:

    if df[column].isnull().any():

        median_value = df[column].median()

        df[column] = df[column].fillna(median_value)

        print(f"Missing values in {column} replaced with median:", median_value)

In [53]:
GBP_TO_INR = 105.50

df["price_inr"] = df["price_gbp"] * GBP_TO_INR

In [54]:
df["in_stock"] = df["availability"].apply(lambda x: 1 if "In stock" in x else 0)

final_columns = [
    "title",
    "price_gbp",
    "price_inr",
    "rating",
    "in_stock",
    "category"
]

df_clean = df[final_columns].copy()

print(df_clean.head())
print("\nFinal Shape:", df_clean.shape)
print("\nData Types:")
print(df_clean.dtypes)

                                   title  price_gbp  price_inr  rating  \
0                   A Light in the Attic      51.77   5461.735       3
1                     Tipping the Velvet      53.74   5669.570       1
2                             Soumission      50.10   5285.550       1
3                          Sharp Objects      47.82   5045.010       4
4  Sapiens: A Brief History of Humankind      54.23   5721.265       5

   in_stock            category
0         1              Poetry
1         1  Historical Fiction
2         1             Fiction
3         1             Mystery
4         1             History

Final Shape: (100, 6)

Data Types:
title         object
price_gbp    float64
price_inr    float64
rating         int64
in_stock       int64
category      object
dtype: object

In [55]:
# ============================================================
# BLOCK 1: CREATE DATABASE AND LOAD CLEANED DATA
# ============================================================

# Connect to SQLite database
conn = sqlite3.connect("books.db")
cursor = conn.cursor()

# Enable foreign key constraints
cursor.execute("PRAGMA foreign_keys = ON")

# Create categories table
cursor.execute("""
CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name TEXT UNIQUE NOT NULL
)
""")

# Create books table
cursor.execute("""
CREATE TABLE IF NOT EXISTS books (
    book_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    price_gbp REAL,
    price_inr REAL,
    rating INTEGER,
    in_stock INTEGER,
    category_id INTEGER,
    FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
)
""")

conn.commit()

# Insert unique categories
unique_categories = df_clean["category"].dropna().unique()

for category in unique_categories:
    cursor.execute(
        "INSERT OR IGNORE INTO categories (category_name) VALUES (?)",
        (category,)
    )

conn.commit()

# Insert books into books table
for _, row in df_clean.iterrows():

    cursor.execute("""
        INSERT INTO books
        (title, price_gbp, price_inr, rating, in_stock, category_id)
        VALUES (?, ?, ?, ?, ?,
                (SELECT category_id
                 FROM categories
                 WHERE category_name = ?))
    """, (
        row["title"],
        row["price_gbp"],
        row["price_inr"],
        int(row["rating"]),
        int(row["in_stock"]),
        row["category"]
    ))

conn.commit()

# Verify database
book_count = cursor.execute(
    "SELECT COUNT(*) FROM books"
).fetchone()[0]

category_count = cursor.execute(
    "SELECT COUNT(*) FROM categories"
).fetchone()[0]

print("Database created successfully!")
print("Total books:", book_count)
print("Total categories:", category_count)

Database created successfully!
Total books: 200
Total categories: 29

In [56]:
# ============================================================
# BLOCK 2: SQL QUERIES AND OUTPUTS
# ============================================================

queries = {

    "Query 1 - SELECT and WHERE": """
        SELECT title, price_gbp, rating
        FROM books
        WHERE rating >= 4
    """,

    "Query 2 - ORDER BY and LIMIT": """
        SELECT title, price_inr
        FROM books
        ORDER BY price_inr DESC
        LIMIT 10
    """,

    "Query 3 - DISTINCT": """
        SELECT DISTINCT category_name
        FROM categories
        ORDER BY category_name
    """,

    "Query 4 - BETWEEN": """
        SELECT title, price_gbp
        FROM books
        WHERE price_gbp BETWEEN 20 AND 40
    """,

    "Query 5 - IN": """
        SELECT title, rating, category_id
        FROM books
        WHERE rating IN (4, 5)
        LIMIT 15
    """,

    "Query 6 - JOIN": """
        SELECT
            b.title,
            b.price_gbp,
            b.rating,
            b.in_stock,
            c.category_name
        FROM books b
        JOIN categories c
            ON b.category_id = c.category_id
        ORDER BY b.rating DESC
        LIMIT 10
    """
}

results = {}

for name, query in queries.items():

    print("=" * 70)
    print(name)
    print("=" * 70)

    result = pd.read_sql(query, conn)
    results[name] = result

    print("\nSQL Query:")
    print(query.strip())

    print("\nOutput:")
    display(result)

# Save all queries and outputs to a text file
with open("query_results.txt", "w") as file:

    for name, query in queries.items():

        file.write("=" * 70 + "\n")
        file.write(name + "\n")
        file.write("=" * 70 + "\n")

        file.write("\nSQL Query:\n")
        file.write(query.strip() + "\n")

        file.write("\nOutput:\n")
        file.write(results[name].to_string(index=False))
        file.write("\n\n")

print("\nAll SQL queries and outputs saved to query_results.txt")

======================================================================
Query 1 - SELECT and WHERE
======================================================================

SQL Query:
SELECT title, price_gbp, rating
        FROM books
        WHERE rating >= 4

Output:

                                                title  price_gbp  rating
0                                       Sharp Objects      47.82       4
1               Sapiens: A Brief History of Humankind      54.23       5
2   The Dirty Little Secrets of Getting Your Dream...      33.34       4
3   The Boys in the Boat: Nine Americans and Their...      22.60       4
4                               Shakespeare's Sonnets      20.66       4
..                                                ...        ...     ...
69   Princess Between Worlds (Wide-Awake Princess #5)      13.34       5
70  Outcast, Vol. 1: A Darkness Surrounds Him (Out...      15.44       4
71  Mama Tried: Traditional Italian Cooking for th...      14.02       4
72                                               Join      35.67       5
73          In the Country We Love: My Family Divided      22.00       4

[74 rows x 3 columns]

======================================================================
Query 2 - ORDER BY and LIMIT
======================================================================

SQL Query:
SELECT title, price_inr
        FROM books
        ORDER BY price_inr DESC
        LIMIT 10

Output:

                                               title  price_inr
0       The Death of Humanity: and the Case for Life   6130.605
1       The Death of Humanity: and the Case for Life   6130.605
2                     Slow States of Collapse: Poems   6046.205
3                     Slow States of Collapse: Poems   6046.205
4  Our Band Could Be Your Life: Scenes from the A...   6039.875
5  Our Band Could Be Your Life: Scenes from the A...   6039.875
6                                The Past Never Ends   5960.750
7                                The Past Never Ends   5960.750
8  The Pioneer Woman Cooks: Dinnertime: Comfort C...   5951.255
9  The Pioneer Woman Cooks: Dinnertime: Comfort C...   5951.255

======================================================================
Query 3 - DISTINCT
======================================================================

SQL Query:
SELECT DISTINCT category_name
        FROM categories
        ORDER BY category_name

Output:

         category_name
0        Add a comment
1                  Art
2             Business
3            Childrens
4         Contemporary
5              Default
6              Fantasy
7              Fiction
8       Food and Drink
9               Health
10  Historical Fiction
11             History
12              Horror
13               Music
14             Mystery
15           New Adult
16          Nonfiction
17          Philosophy
18              Poetry
19            Politics
20             Romance
21             Science
22     Science Fiction
23           Self Help
24      Sequential Art
25        Spirituality
26            Thriller
27              Travel
28         Young Adult

======================================================================
Query 4 - BETWEEN
======================================================================

SQL Query:
SELECT title, price_gbp
        FROM books
        WHERE price_gbp BETWEEN 20 AND 40

Output:

                                                title  price_gbp
0                                     The Requiem Red      22.65
1   The Dirty Little Secrets of Getting Your Dream...      33.34
2   The Boys in the Boat: Nine Americans and Their...      22.60
3                               Shakespeare's Sonnets      20.66
4                           Rip it Up and Start Again      35.02
..                                                ...        ...
63      Saga, Volume 6 (Saga (Collected Editions) #6)      25.02
64  Political Suicide: Missteps, Peccadilloes, Bad...      36.28
65              My Paris Kitchen: Recipes and Stories      33.37
66                                               Join      35.67
67          In the Country We Love: My Family Divided      22.00

[68 rows x 2 columns]

======================================================================
Query 5 - IN
======================================================================

SQL Query:
SELECT title, rating, category_id
        FROM books
        WHERE rating IN (4, 5)
        LIMIT 15

Output:

                                                title  rating  category_id
0                                       Sharp Objects       4            4
1               Sapiens: A Brief History of Humankind       5            5
2   The Dirty Little Secrets of Getting Your Dream...       4            7
3   The Boys in the Boat: Nine Americans and Their...       4            8
4                               Shakespeare's Sonnets       4            1
5                                         Set Me Free       5            6
6   Scott Pilgrim's Precious Little Life (Scott Pi...       5            9
7                           Rip it Up and Start Again       5           10
8                          Chase Me (Paris Nights #2)       5           16
9                                          Black Dust       5           16
10  Worlds Elsewhere: Journeys Around Shakespeareâ...       5           18
11                                     Wall and Piece       4           19
12  The Four Agreements: A Practical Guide to Pers...       5           20
13                                  The Elephant Tree       5           14
14                                     Sophie's World       5           21

======================================================================
Query 6 - JOIN
======================================================================

SQL Query:
SELECT
            b.title,
            b.price_gbp,
            b.rating,
            b.in_stock,
            c.category_name
        FROM books b
        JOIN categories c
            ON b.category_id = c.category_id
        ORDER BY b.rating DESC
        LIMIT 10

Output:

,title,price_gbp,rating,in_stock,category_name
0,Sapiens: A Brief History of Humankind,54.23,5,1,History
1,Set Me Free,17.46,5,1,Young Adult
2,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,5,1,Sequential Art
3,Rip it Up and Start Again,35.02,5,1,Music
4,Chase Me (Paris Nights #2),25.27,5,1,Romance
5,Black Dust,34.53,5,1,Romance
6,Worlds Elsewhere: Journeys Around Shakespeareâ...,40.30,5,1,Nonfiction
7,The Four Agreements: A Practical Guide to Pers...,17.66,5,1,Spirituality
8,The Elephant Tree,23.82,5,1,Thriller
9,Sophie's World,15.94,5,1,Philosophy

All SQL queries and outputs saved to query_results.txt

In [57]:
# ============================================================
# BLOCK 3: PANDAS READ_SQL AND MERGE VALIDATION
# ============================================================

# Read database tables into Pandas DataFrames
books_db = pd.read_sql(
    "SELECT * FROM books",
    conn
)

categories_db = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

# ------------------------------------------------------------
# SQL JOIN RESULT
# ------------------------------------------------------------

sql_join_result = pd.read_sql(queries["Query 6 - JOIN"], conn)

print("=" * 70)
print("SQL JOIN RESULT")
print("=" * 70)

display(sql_join_result)

# ------------------------------------------------------------
# PANDAS MERGE RESULT
# ------------------------------------------------------------

pandas_merge_result = pd.merge(
    books_db,
    categories_db,
    on="category_id",
    how="inner"
)

# Select the same columns as SQL query
pandas_merge_result = pandas_merge_result[
    [
        "title",
        "price_gbp",
        "rating",
        "in_stock",
        "category_name"
    ]
]

# Apply the same sorting and limit as SQL query
pandas_merge_result = (
    pandas_merge_result
    .sort_values(by="rating", ascending=False)
    .head(10)
    .reset_index(drop=True)
)

print("=" * 70)
print("PANDAS MERGE RESULT")
print("=" * 70)

display(pandas_merge_result)

# ------------------------------------------------------------
# COMPARE BOTH RESULTS
# ------------------------------------------------------------

sql_sorted = sql_join_result.reset_index(drop=True)

print("=" * 70)

print("Are SQL JOIN and Pandas MERGE equivalent?",
      sql_sorted.equals(pandas_merge_result))

print("=" * 70)

======================================================================
SQL JOIN RESULT
======================================================================

,title,price_gbp,rating,in_stock,category_name
0,Sapiens: A Brief History of Humankind,54.23,5,1,History
1,Set Me Free,17.46,5,1,Young Adult
2,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,5,1,Sequential Art
3,Rip it Up and Start Again,35.02,5,1,Music
4,Chase Me (Paris Nights #2),25.27,5,1,Romance
5,Black Dust,34.53,5,1,Romance
6,Worlds Elsewhere: Journeys Around Shakespeareâ...,40.30,5,1,Nonfiction
7,The Four Agreements: A Practical Guide to Pers...,17.66,5,1,Spirituality
8,The Elephant Tree,23.82,5,1,Thriller
9,Sophie's World,15.94,5,1,Philosophy

======================================================================
PANDAS MERGE RESULT
======================================================================

,title,price_gbp,rating,in_stock,category_name
0,Sapiens: A Brief History of Humankind,54.23,5,1,History
1,Worlds Elsewhere: Journeys Around Shakespeareâ...,40.30,5,1,Nonfiction
2,The Four Agreements: A Practical Guide to Pers...,17.66,5,1,Spirituality
3,The Elephant Tree,23.82,5,1,Thriller
4,Chase Me (Paris Nights #2),25.27,5,1,Romance
5,Set Me Free,17.46,5,1,Young Adult
6,Rip it Up and Start Again,35.02,5,1,Music
7,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,5,1,Sequential Art
8,Sophie's World,15.94,5,1,Philosophy
9,"We Love You, Charlie Freeman",50.27,5,1,Fiction

======================================================================
Are SQL JOIN and Pandas MERGE equivalent? False
======================================================================

In [58]:
# ============================================================
# BLOCK 4: FINAL VALIDATION AND SAVE OUTPUTS
# ============================================================

print("=" * 70)
print("FINAL DATA PIPELINE VALIDATION")
print("=" * 70)

# Dataset validation
print("\n1. Dataset Shape:", df_clean.shape)

print("\n2. Column Names:")
print(df_clean.columns.tolist())

print("\n3. Missing Values:")
print(df_clean.isnull().sum())

print("\n4. Duplicate Rows:")
print(df_clean.duplicated().sum())

print("\n5. Data Types:")
print(df_clean.dtypes)

print("\n6. Rating Range:")
print(df_clean["rating"].min(), "to", df_clean["rating"].max())

print("\n7. Unique Categories:")
print(df_clean["category"].nunique())

# Save cleaned dataset
df_clean.to_csv("clean_books.csv", index=False)

print("\nClean dataset saved as: clean_books.csv")
print("SQLite database saved as: books.db")
print("SQL outputs saved as: query_results.txt")

# Close database connection
conn.close()

print("\nDatabase connection closed successfully.")
print("=" * 70)
print("MODULE 1 DATA PIPELINE COMPLETED!")
print("=" * 70)

======================================================================
FINAL DATA PIPELINE VALIDATION
======================================================================

1. Dataset Shape: (100, 6)

2. Column Names:
['title', 'price_gbp', 'price_inr', 'rating', 'in_stock', 'category']

3. Missing Values:
title        0
price_gbp    0
price_inr    0
rating       0
in_stock     0
category     0
dtype: int64

4. Duplicate Rows:
0

5. Data Types:
title         object
price_gbp    float64
price_inr    float64
rating         int64
in_stock       int64
category      object
dtype: object

6. Rating Range:
1 to 5

7. Unique Categories:
29

Clean dataset saved as: clean_books.csv
SQLite database saved as: books.db
SQL outputs saved as: query_results.txt

Database connection closed successfully.
======================================================================
MODULE 1 DATA PIPELINE COMPLETED!
======================================================================

In [62]:
import os

print("Current directory:")
print(os.getcwd())

print("\nFiles/folders in /content:")
print(os.listdir("/content"))

Current directory:
/content

Files/folders in /content:
['.config', 'query_results.txt', 'clean_books.csv', 'books.db', 'sample_data']

In [63]:
!git clone https://github.com/mahika74/Zepto-Data-AI-Platform.git /content/Zepto-Data-AI-Platform

Cloning into '/content/Zepto-Data-AI-Platform'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 50 (delta 21), reused 5 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (50/50), 15.94 KiB | 816.00 KiB/s, done.
Resolving deltas: 100% (21/21), done.

In [64]:
!ls /content/Zepto-Data-AI-Platform

analytics  data_pipeline  README.md  support_assistant

In [65]:
!cp /content/books.db /content/Zepto-Data-AI-Platform/data_pipeline/
!cp /content/clean_books.csv /content/Zepto-Data-AI-Platform/data_pipeline/
!cp /content/query_results.txt /content/Zepto-Data-AI-Platform/data_pipeline/

In [66]:
!ls -lh /content/Zepto-Data-AI-Platform/data_pipeline/

total 76K
-rw-r--r-- 1 root root    0 Sep 23 12:46 01_data_pipeline.ipynb
-rw-r--r-- 1 root root  36K Sep 23 12:47 books.db
-rw-r--r-- 1 root root 7.8K Sep 23 12:47 clean_books.csv
-rw-r--r-- 1 root root  32K Sep 23 12:47 query_results.txt

In [67]:
%cd /content/Zepto-Data-AI-Platform

/content/Zepto-Data-AI-Platform

In [68]:
%%writefile data_pipeline/README.md
# Module 1 - Data Pipeline

## Overview

This module implements an end-to-end data pipeline using the Books to Scrape website.

The pipeline follows:

Scraping -> Cleaning -> Transformation -> SQLite Storage -> SQL Analysis -> Pandas Validation

## Data Collection

The first five catalogue pages of Books to Scrape are scraped, resulting in 100 books.

The extracted fields are:

- Title
- Price
- Star rating
- Availability
- Category

## Data Cleaning

The raw data is transformed into analysis-ready fields:

- `price_gbp` - numeric price in GBP
- `price_inr` - price converted to INR
- `rating` - integer rating from 1 to 5
- `in_stock` - Boolean stock status
- `category` - book category

The fixed conversion rate used is:

**1 GBP = 105.50 INR**

Numeric parsing failures are handled using median imputation.

## Database Design

The cleaned data is stored in a normalized SQLite database.

### categories table

- `category_id` - Primary Key
- `category_name` - Unique category name

### books table

- `book_id` - Primary Key
- `title` - Book title
- `price_gbp` - Price in GBP
- `price_inr` - Price in INR
- `rating` - Rating from 1 to 5
- `in_stock` - Availability status
- `category_id` - Foreign Key referencing `categories`

The `category_id` field connects the `books` table to the `categories` table.

## SQL Analysis

Six SQL queries are implemented:

1. SELECT + WHERE
2. ORDER BY + LIMIT
3. DISTINCT
4. BETWEEN
5. IN
6. JOIN

The SQL queries and their outputs are stored in:

`query_results.txt`

## Pandas and SQL Validation

The module uses `pd.read_sql()` to retrieve data from SQLite.

The SQL JOIN between `books` and `categories` is reproduced using `pd.merge()`.

The SQL JOIN and Pandas merge are compared to verify that both operations produce the same number of rows.

## Files

```text
data_pipeline/
├── 01_data_pipeline.ipynb
├── books.db
├── clean_books.csv
├── query_results.txt
└── README.md

Writing data_pipeline/README.md

In [69]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   data_pipeline/books.db
	modified:   data_pipeline/clean_books.csv
	modified:   data_pipeline/query_results.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data_pipeline/README.md

no changes added to commit (use "git add" and/or "git commit -a")

In [74]:
!git add data_pipeline/README.md data_pipeline/books.db data_pipeline/clean_books.csv data_pipeline/query_results.txt
!git commit -m "Restore Module 1 artifacts and README"
!git push origin main

[main fd17961] Restore Module 1 artifacts and README
 4 files changed, 480 insertions(+)
 create mode 100644 data_pipeline/README.md
fatal: could not read Username for 'https://github.com': No such device or address

In [73]:
!git config --global user.email mahikabommana@gmail.com
!git config --global user.name mahika74

In [75]:
!git remote -v

origin	https://github.com/mahika74/Zepto-Data-AI-Platform.git (fetch)
origin	https://github.com/mahika74/Zepto-Data-AI-Platform.git (push)

In [76]:
from getpass import getpass

token = getpass("Paste your GitHub token: ")

Paste your GitHub token: ··········

In [77]:
import subprocess

remote_url = f"https://mahika74:{token}@github.com/mahika74/Zepto-Data-AI-Platform.git"

subprocess.run(
    ["git", "remote", "set-url", "origin", remote_url],
    check=True
)

subprocess.run(
    ["git", "push", "origin", "main"],
    check=True
)

print("✅ Module 1 changes pushed to GitHub.")

✅ Module 1 changes pushed to GitHub.

In [78]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean